/* tslint:disable */
/* eslint-disable */
/**
 * Online School
 * Online School Application is where students and teachers meet together
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudentStatus,
    StudentStatusFromJSON,
    StudentStatusFromJSONTyped,
    StudentStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface StudentAllOf
 */
export interface StudentAllOf {
    /**
     * 
     * @type {string}
     * @memberof StudentAllOf
     */
    id: string;
    /**
     * 
     * @type {StudentStatus}
     * @memberof StudentAllOf
     */
    status: StudentStatus;
}

export function StudentAllOfFromJSON(json: any): StudentAllOf {
    return StudentAllOfFromJSONTyped(json, false);
}

export function StudentAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': StudentStatusFromJSON(json['status']),
    };
}

export function StudentAllOfToJSON(value?: StudentAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': StudentStatusToJSON(value.status),
    };
}


